project_id = "scacnshkxfrahxarjrwb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.google-oauth]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false

[functions.get-google-config]
verify_jwt = false